2023-09-24T07:23:12.935Z 	 info: Azurite Blob service is starting on 127.0.0.1:10000
2023-09-24T07:23:12.936Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-09-24T07:23:12.937Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-09-24T07:23:12.943Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2023-09-24T07:23:12.943Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2023-09-24T07:23:12.943Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2023-09-24T07:23:12.943Z 	 info: BlobGCManager:markSweep() Get all extents.
2023-09-24T07:23:12.944Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2023-09-24T07:23:12.945Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2023-09-24T07:23:12.945Z 	 info: BlobGCManager:markSweep() Get referred extents.
2023-09-24T07:23:12.946Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-09-24T07:23:12.946Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 3ms.
2023-09-24T07:23:12.946Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2023-09-24T07:23:12.947Z 	 info: Azurite Blob service successfully listens on http://127.0.0.1:10000
2023-09-24T07:23:12.947Z 	 info: Azurite Queue service is starting on 127.0.0.1:10001
2023-09-24T07:23:12.947Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-09-24T07:23:12.947Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-09-24T07:23:12.951Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2023-09-24T07:23:12.951Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2023-09-24T07:23:12.951Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-09-24T07:23:12.951Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-09-24T07:23:12.952Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2023-09-24T07:23:12.952Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-09-24T07:23:12.952Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-09-24T07:23:12.952Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-09-24T07:23:12.952Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-09-24T07:23:12.952Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-09-24T07:23:12.952Z 	 info: Azurite Queue service successfully listens on http://127.0.0.1:10001
2023-09-24T07:23:12.952Z 	 info: Azurite Table service is starting on 127.0.0.1:10002
2023-09-24T07:23:12.952Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-09-24T07:23:12.952Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-09-24T07:23:12.954Z 	 info: Azurite Table service successfully listens on http://127.0.0.1:10002
2023-09-24T07:23:23.053Z 	 info: Azurite Blob service is closing...
2023-09-24T07:23:23.054Z 	 info: Azurite Queue service is closing...
2023-09-24T07:23:23.054Z 	 info: Azurite Table service is closing...
2023-09-24T07:23:23.055Z 	 info: BlobGCManager:close() Start closing BlobGCManager. Set status to Closing.
2023-09-24T07:23:23.055Z 	 info: QueueGCManager:close() Start closing QueueGCManager, set status to Closing.
2023-09-24T07:23:23.055Z 	 info: BlobGCManager:start() Mark and sweep loop is closed.
2023-09-24T07:23:23.055Z 	 info: BlobGCManager:close() BlobGCManager successfully closed. Set status to Closed.
2023-09-24T07:23:23.055Z 	 info: QueueGCManager:start() Mark and sweep loop is closed.
2023-09-24T07:23:23.055Z 	 info: QueueGCManager:close() QueueGCManager successfully closed, set status to Closed.
2023-09-24T07:23:23.055Z 	 info: Azurite Table service successfully closed
2023-09-24T07:23:23.055Z 	 info: Azurite Blob service successfully closed
2023-09-24T07:23:23.055Z 	 info: Azurite Queue service successfully closed
