2023-09-23T19:59:47.945Z 	 info: Azurite Blob service is starting on 127.0.0.1:10000
2023-09-23T19:59:47.946Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-09-23T19:59:47.946Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-09-23T19:59:47.952Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2023-09-23T19:59:47.953Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2023-09-23T19:59:47.953Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2023-09-23T19:59:47.953Z 	 info: BlobGCManager:markSweep() Get all extents.
2023-09-23T19:59:47.953Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2023-09-23T19:59:47.954Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2023-09-23T19:59:47.954Z 	 info: BlobGCManager:markSweep() Get referred extents.
2023-09-23T19:59:47.955Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-09-23T19:59:47.955Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 2ms.
2023-09-23T19:59:47.955Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2023-09-23T19:59:47.955Z 	 info: Azurite Blob service successfully listens on http://127.0.0.1:10000
2023-09-23T19:59:47.956Z 	 info: Azurite Queue service is starting on 127.0.0.1:10001
2023-09-23T19:59:47.956Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-09-23T19:59:47.956Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-09-23T19:59:47.960Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2023-09-23T19:59:47.960Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-09-23T19:59:47.960Z 	 info: Azurite Queue service successfully listens on http://127.0.0.1:10001
2023-09-23T19:59:47.961Z 	 info: Azurite Table service is starting on 127.0.0.1:10002
2023-09-23T19:59:47.961Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-09-23T19:59:47.961Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-09-23T19:59:47.963Z 	 info: Azurite Table service successfully listens on http://127.0.0.1:10002
2023-09-23T19:59:54.444Z 	 info: Azurite Blob service is closing...
2023-09-23T19:59:54.445Z 	 info: Azurite Queue service is closing...
2023-09-23T19:59:54.446Z 	 info: Azurite Table service is closing...
2023-09-23T19:59:54.447Z 	 info: BlobGCManager:close() Start closing BlobGCManager. Set status to Closing.
2023-09-23T19:59:54.448Z 	 info: QueueGCManager:close() Start closing QueueGCManager, set status to Closing.
2023-09-23T19:59:54.448Z 	 info: BlobGCManager:start() Mark and sweep loop is closed.
2023-09-23T19:59:54.449Z 	 info: BlobGCManager:close() BlobGCManager successfully closed. Set status to Closed.
2023-09-23T19:59:54.449Z 	 info: QueueGCManager:start() Mark and sweep loop is closed.
2023-09-23T19:59:54.449Z 	 info: QueueGCManager:close() QueueGCManager successfully closed, set status to Closed.
2023-09-23T19:59:54.449Z 	 info: Azurite Table service successfully closed
2023-09-23T19:59:54.449Z 	 info: Azurite Blob service successfully closed
2023-09-23T19:59:54.449Z 	 info: Azurite Queue service successfully closed
